export const COMMON_ROLES = [
    "Software Engineer",
    "Full Stack Developer",
    "Frontend Engineer",
    "Backend Engineer",
    "Data Scientist",
    "Product Manager",
    "Project Manager",
    "UX/UI Designer",
    "DevOps Engineer",
    "QA Engineer",
    "Mobile Developer",
    "Technical Architect",
    "Support Engineer",
    "Data Analyst",
    "Marketing Specialist",
    "Sales Representative",
    "Accountant",
    "HR Manager",
    "Customer Success Manager",
];

export const COMMON_INDUSTRIES = [
    "Technology/Software",
    "Finance/Banking",
    "Healthcare/Medical",
    "Education/EdTech",
    "Retail/E-commerce",
    "Manufacturing",
    "Consulting",
    "Marketing/Advertising",
    "Energy/Utilities",
    "Government/Public Sector",
    "Entertainment/Media",
    "Logistics/Transportation",
    "Real Estate",
];
