export const ENV = {
    OPENAI_API_KEY: (process.env.EXPO_PUBLIC_OPENAI_API_KEY || '').trim(),
    FIREBASE_API_KEY: (process.env.EXPO_PUBLIC_FIREBASE_API_KEY || '').trim(),
    FIREBASE_AUTH_DOMAIN: (process.env.EXPO_PUBLIC_FIREBASE_AUTH_DOMAIN || '').trim(),
    FIREBASE_PROJECT_ID: (process.env.EXPO_PUBLIC_FIREBASE_PROJECT_ID || '').trim(),
    FIREBASE_STORAGE_BUCKET: (process.env.EXPO_PUBLIC_FIREBASE_STORAGE_BUCKET || '').trim(),
    FIREBASE_MESSAGING_SENDER_ID: (process.env.EXPO_PUBLIC_FIREBASE_MESSAGING_SENDER_ID || '').trim(),
    FIREBASE_APP_ID_IOS: (process.env.EXPO_PUBLIC_FIREBASE_APP_ID_IOS || '').trim(),
    FIREBASE_APP_ID_ANDROID: (process.env.EXPO_PUBLIC_FIREBASE_APP_ID_ANDROID || '').trim(),
    API_URL: (process.env.EXPO_PUBLIC_API_URL || '').trim(),
    PERPLEXITY_API_KEY: (process.env.EXPO_PUBLIC_PERPLEXITY_API_KEY || '').trim(),
    STRIPE_PUBLISHABLE_KEY: (process.env.EXPO_PUBLIC_STRIPE_PUBLISHABLE_KEY || '').trim(),
    GOOGLE_WEB_CLIENT_ID: (process.env.EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID || '').trim(),
    GOOGLE_IOS_CLIENT_ID: (process.env.EXPO_PUBLIC_GOOGLE_IOS_CLIENT_ID || '').trim(),
    GOOGLE_ANDROID_CLIENT_ID: (process.env.EXPO_PUBLIC_GOOGLE_ANDROID_CLIENT_ID || '').trim(),
    FIREBASE_APP_ID_WEB: (process.env.EXPO_PUBLIC_FIREBASE_APP_ID_WEB || '').trim(),
    ADMIN_EMAIL: (process.env.EXPO_PUBLIC_ADMIN_EMAIL || 'support@riresume.com').trim(),
};
